server:
  port: 8083  
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  
spring:
  application:
    name: API-GATEWAY
        
    
  cloud:
    gateway:
      routes:
      - id: COLLEGE-SERVICE
        uri:
          lb://COLLEGE-SERVICE
        predicates:
        - Path=/college/**
          
          
      - id: STUDENT-SERVICE  
        uri:
           lb://STUDENT-SERVICE
        predicates:
        - Path=/student/** 
           
    


    
           
          
          
          
          
     
      